### ISSUE TITLE
keyError:('run_id', 0)

### ISSUE THREAD

**Issue by gongshuai0606** [wedeling/EasySurrogate#24]
Hi, there is an error `keyError:('run_id', 0)` in line 136 in campaign.py when I run the train_DAS_surrogate.py of tests/deep_active_subspaces

**Comment by wedeling** [comment]
Hi @gongshuai0606 I saw you closed this, did you manage to fix it? I don't seem to have issues on my end.

In any case, I'm not too happy with the `tests/deep_active_subspace` markdown tutorial, so I've added another based on a jupyter notebook: `tutorial/deep_active_subspaces_HIV`.

**Comment by gongshuai0606** [comment]
> Hi @gongshuai0606 I saw you closed this, did you manage to fix it? I don't seem to have issues on my end.
> 
> In any case, I'm not too happy with the `tests/deep_active_subspace` markdown tutorial, so I've added another based on a jupyter notebook: `tutorial/deep_active_subspaces_HIV`.

Thank you for your kind reply. In fact, I didn't fix it. I will have a try at the `tutorial/deep_active_subspaces_HIV`.

**Comment by wedeling** [comment]
> > Hi @gongshuai0606 I saw you closed this, did you manage to fix it? I don't seem to have issues on my end.
> > In any case, I'm not too happy with the `tests/deep_active_subspace` markdown tutorial, so I've added another based on a jupyter notebook: `tutorial/deep_active_subspaces_HIV`.
> 
> Thank you for your kind reply. In fact, I didn't fix it. I will have a try at the `tutorial/deep_active_subspaces_HIV`.

Ok let me know if you have issues. I could also try to fix the original error if you'd like., if you post a larger error message.
